#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'
class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 84)

  def parse(file, file_name)
    @file_name = file_name
    @q = Scanner.new.scan(file)
    @yydebug = true
    do_parse
  end

  def next_token
    @q.shift
  end

  def on_error(t, v, values)
    if v
      line = v[0]
      v = v[1]
    else
      line = 'last'
    end
    raise Racc::ParseError, "#{@file_name}:#{line}: syntax error on #{v.inspect}"
  end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     4,     6,     8,     9,    12,    13,    14,    12,    18,    20,
    22,    23,     8,    24,    25,    27,     8,     8 ]

racc_action_check = [
     1,     2,     3,     4,     5,     6,     8,    10,    12,    14,
    15,    17,    19,    20,    22,    23,    28,    29 ]

racc_action_pointer = [
   nil,     0,    -1,    -3,     3,     1,     2,   nil,     0,   nil,
     4,   nil,     4,   nil,     2,     8,   nil,     9,   nil,     7,
     5,   nil,    11,    11,   nil,   nil,   nil,   nil,    11,    12 ]

racc_action_default = [
   -13,   -17,   -17,    -2,   -17,   -17,   -17,   -14,   -15,    30,
   -10,    -4,   -17,   -13,   -17,    -1,    -5,   -17,    -7,    -3,
   -17,   -11,   -17,    -9,   -16,   -13,   -13,    -8,   -12,    -6 ]

racc_goto_table = [
     3,    11,     1,    10,    15,     5,    16,     2,    17,    26,
    21,   nil,   nil,    19,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    28,    29 ]

racc_goto_check = [
     6,     7,     1,     4,     5,     3,     7,     2,     8,     9,
    10,   nil,   nil,     6,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     6,     6 ]

racc_goto_pointer = [
   nil,     2,     7,     3,    -2,    -6,     0,    -4,    -4,   -14,
    -5,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     7 ]

racc_reduce_table = [
  0, 0, :racc_error,
  4, 10, :_reduce_1,
  1, 11, :_reduce_none,
  3, 12, :_reduce_3,
  1, 13, :_reduce_4,
  2, 13, :_reduce_5,
  5, 16, :_reduce_6,
  1, 17, :_reduce_none,
  1, 18, :_reduce_none,
  0, 18, :_reduce_9,
  0, 14, :_reduce_10,
  2, 14, :_reduce_11,
  3, 19, :_reduce_12,
  0, 15, :_reduce_13,
  2, 15, :_reduce_14,
  1, 20, :_reduce_15,
  4, 20, :_reduce_16 ]

racc_reduce_n = 17

racc_shift_n = 30

racc_token_table = {
  false => 0,
  :error => 1,
  :TYPE => 2,
  :NAME => 3,
  :NUMBER => 4,
  :IDENT => 5,
  "(" => 6,
  :STRING => 7,
  ")" => 8 }

racc_nt_base = 9

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "TYPE",
  "NAME",
  "NUMBER",
  "IDENT",
  "\"(\"",
  "STRING",
  "\")\"",
  "$start",
  "dds",
  "file_level",
  "record_level",
  "field_level",
  "key_field_level",
  "functions",
  "data_field",
  "length",
  "decimal_positions",
  "key_field",
  "function" ]

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 10)
  def _reduce_1(val, _values)
                      RootNode.new(val[0], val[1], val[2], val[3])
                
  end
.,.,

# reduce 2 omitted

module_eval(<<'.,.,', 'parser.y', 17)
  def _reduce_3(val, _values)
                      RecordNode.new(@file_name, val[0][0], val[0][1], val[1][1], val[2])
                
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 22)
  def _reduce_4(val, _values)
                          [val[0]]                
                   
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 26)
  def _reduce_5(val, _values)
                        val[0].push(val[1])
                  
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 31)
  def _reduce_6(val, _values)
                        DataFieldNode.new(@file_name, val[0][0], val[0][1], val[1][1], val[2][1], val[3][1], val[4])
                  
  end
.,.,

# reduce 7 omitted

# reduce 8 omitted

module_eval(<<'.,.,', 'parser.y', 39)
  def _reduce_9(val, _values)
                              [nil, nil]
                        
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 45)
  def _reduce_10(val, _values)
                            @key_sequence = 0
                        {}
                      
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 50)
  def _reduce_11(val, _values)
                            @key_sequence += 1
                        val[1].key_sequence = @key_sequence 
                        val[0].store(val[1].name, val[1])
                        val[0]
                      
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 59)
  def _reduce_12(val, _values)
                  KeyFieldNode.new(@file_name, val[0][0], val[0][1], val[1][1], val[2])
            
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 64)
  def _reduce_13(val, _values)
                      []
                
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 68)
  def _reduce_14(val, _values)
                      val[0].push(val[1])
                
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 73)
  def _reduce_15(val, _values)
                   FunctionNode.new(@file_name, val[0][0], val[0][1])
            
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 77)
  def _reduce_16(val, _values)
                   FunctionNode.new(@file_name, val[0][0], val[0][1], val[2][1])
            
  end
.,.,

def _reduce_none(val, _values)
  val[0]
end

end   # class Parser
