#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'
class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 104)

  def parse(file, file_name)
    @file_name = file_name
    @q = Scanner.new.scan(file)
    @yydebug = true
    do_parse
  end

  def next_token
    @q.shift
  end

  def on_error(t, v, values)
    if v
      line = v[0]
      v = v[1]
    else
      line = 'last'
    end
    raise Racc::ParseError, "#{@file_name}:#{line}: syntax error on #{v.inspect}"
  end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    19,    28,     8,    18,    30,    23,    24,    11,    12,    15,
     4,    21,     8,     9,    25,    26,    27,     6,    32,    30,
     8,     8,     8,     8 ]

racc_action_check = [
    12,    22,    16,    12,    22,    15,    15,     6,     8,    10,
     1,    13,     3,     4,    17,    18,    21,     2,    26,    28,
    31,    33,    35,    36 ]

racc_action_pointer = [
   nil,    10,    15,     6,    13,   nil,     4,   nil,     1,   nil,
     6,   nil,    -6,     9,   nil,     1,    -4,     6,     5,   nil,
   nil,    13,    -1,   nil,   nil,   nil,     9,   nil,    14,   nil,
   nil,    14,   nil,    15,   nil,    16,    17 ]

racc_action_default = [
   -16,   -23,   -23,    -2,   -23,    -4,   -23,   -17,   -18,    37,
   -13,   -16,   -23,    -1,    -5,   -10,    -3,   -23,   -20,   -22,
   -14,   -23,   -12,   -16,    -9,   -19,   -23,   -16,   -12,   -16,
   -11,    -8,   -21,   -15,   -16,    -7,    -6 ]

racc_goto_table = [
     3,    29,     1,    10,    13,     5,    14,    34,    22,     2,
    20,    16,    17,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    31,   nil,   nil,   nil,    33,   nil,    35,
   nil,   nil,   nil,   nil,    36 ]

racc_goto_check = [
     6,     9,     1,     4,     5,     3,     7,     9,     8,     2,
    10,     6,    12,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     6,   nil,   nil,   nil,     6,   nil,     6,
   nil,   nil,   nil,   nil,     6 ]

racc_goto_pointer = [
   nil,     2,     9,     3,    -2,    -6,     0,    -4,    -7,   -21,
    -3,   nil,     0 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     7,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  4, 12, :_reduce_1,
  1, 13, :_reduce_none,
  3, 14, :_reduce_3,
  0, 15, :_reduce_4,
  2, 15, :_reduce_5,
  5, 18, :_reduce_6,
  4, 18, :_reduce_7,
  3, 18, :_reduce_8,
  1, 19, :_reduce_none,
  0, 19, :_reduce_10,
  1, 20, :_reduce_none,
  0, 20, :_reduce_12,
  0, 16, :_reduce_13,
  2, 16, :_reduce_14,
  3, 21, :_reduce_15,
  0, 17, :_reduce_16,
  2, 17, :_reduce_17,
  1, 22, :_reduce_18,
  4, 22, :_reduce_19,
  1, 23, :_reduce_none,
  3, 23, :_reduce_21,
  1, 23, :_reduce_none ]

racc_reduce_n = 23

racc_shift_n = 37

racc_token_table = {
  false => 0,
  :error => 1,
  :TYPE => 2,
  :NAME => 3,
  :REFERENCE => 4,
  :NUMBER => 5,
  :IDENT => 6,
  "(" => 7,
  ")" => 8,
  :STRING => 9,
  "+" => 10 }

racc_nt_base = 11

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "TYPE",
  "NAME",
  "REFERENCE",
  "NUMBER",
  "IDENT",
  "\"(\"",
  "\")\"",
  "STRING",
  "\"+\"",
  "$start",
  "dds",
  "file_level",
  "record_level",
  "field_level",
  "key_field_level",
  "functions",
  "data_field",
  "length",
  "decimal_positions",
  "key_field",
  "function",
  "primary" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 11)
  def _reduce_1(val, _values)
                              RootNode.new(val[0], val[1], val[2], val[3])
                        
  end
.,.,

# reduce 2 omitted

module_eval(<<'.,.,', 'parser.y', 18)
  def _reduce_3(val, _values)
                              RecordNode.new(@file_name, val[0][0], val[0][1], val[1][1], val[2])
                        
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 23)
  def _reduce_4(val, _values)
                              []                
                        
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 27)
  def _reduce_5(val, _values)
                              val[0].push(val[1])
                        
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 32)
  def _reduce_6(val, _values)
                              DataFieldNode.new(@file_name, val[0][0], val[0][1], val[1][1], val[2][1], val[3][1], val[4])
                        
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 36)
  def _reduce_7(val, _values)
                              DataFieldNode.new(@file_name, val[0][0], val[0][1], val[1][1], "A", val[2][1], val[3])
                        
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 40)
  def _reduce_8(val, _values)
                              DataFieldNode.new(@file_name, val[0][0], val[0][1], nil, val[1][1], nil, val[2])
                        
  end
.,.,

# reduce 9 omitted

module_eval(<<'.,.,', 'parser.y', 47)
  def _reduce_10(val, _values)
                              [nil, nil]
                        
  end
.,.,

# reduce 11 omitted

module_eval(<<'.,.,', 'parser.y', 53)
  def _reduce_12(val, _values)
                              [nil, nil]
                        
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 59)
  def _reduce_13(val, _values)
                              {}
                        
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 63)
  def _reduce_14(val, _values)
                              val[0].store(val[1].name, val[1].key_sequence)
                          val[0]
                        
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 70)
  def _reduce_15(val, _values)
                              KeyFieldNode.new(@file_name, val[0][0], val[0][1], val[1][1], val[2])
                        
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 75)
  def _reduce_16(val, _values)
                              []
                        
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 79)
  def _reduce_17(val, _values)
                              val[0].push(val[1])
                        
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 84)
  def _reduce_18(val, _values)
                              FunctionNode.new(@file_name, val[0][0], val[0][1])
                        
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 88)
  def _reduce_19(val, _values)
                              FunctionNode.new(@file_name, val[0][0], val[0][1], val[2][1])
                        
  end
.,.,

# reduce 20 omitted

module_eval(<<'.,.,', 'parser.y', 95)
  def _reduce_21(val, _values)
                              val[0][1][1] = val[0][1][1] + val[2][1][1]
                          val[0]
                        
  end
.,.,

# reduce 22 omitted

def _reduce_none(val, _values)
  val[0]
end

end   # class Parser
